export const ERROR = {
  VALIDATION: "VALIDATION_ERROR",
  TURNSTILE: "TURNSTILE_FAILED",
  EMAIL: "EMAIL_FAILED",
  INTERNAL: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMIT: "RATE_LIMITED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
} as const;